import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

import { Footer } from "src/components/Layout/Footer";
import { Header } from "src/components/Layout/Header";

const Home: NextPage = () => {
  const pets = [
    "/images/maro.jpg",
    "/images/mugi.jpg",
    "/images/rantarou.jpg",
    "/images/rintarou.jpg",
    "/images/yukiti.jpg",
    "/images/sou.jpg",
    "/images/kotarou.jpg",
    "/images/sena.jpg",
  ];
  // const pets = ["maro", "mugi", "rantarou", "rintarou", "yukiti", "sou", "kotarou" ]
  // const pet = pets.map((img) => {
  //   return (
  //     `/images/${img}.jpg`
  //   )
  // })
  // console.log(pet)

  return (
    <>
      <Header title="satoWa">
        <Head>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      </Header>

      <main>
        <div className="flex justify-items-center lg:mx-auto">
          <div className="lg:mx-auto">
            <Image
              src="/images/dog.jpg"
              alt="Picture of the author"
              width={1440}
              height={500}
              objectFit="contain"
            />
          </div>
        </div>

        <div className="m-auto">
          <div>
            <div className="flex justify-center pt-3 mb-3 text-3xl underline">
              New Family
            </div>
          </div>
          <div className="text-center">
            <div className="grid grid-cols-2 gap-y-5 justify-items-center sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 xl:grid-cols-6 2xl:grid-cols-7">
              {pets.map((img) => {
                return (
                  <div
                    key={img}
                    className="p-4 w-40 text-center bg-green-800 rounded-lg shadow-xl"
                  >
                    <div className="flex justify-center">
                      <Image
                        className="rounded-full object-none"
                        src={img}
                        width={128}
                        height={128}
                        alt="pet"
                      />
                    </div>
                    <div className="py-2 text-white">Name</div>
                    <button className="text-orange-600">Tap</button>
                  </div>
                );
              })}
            </div>
            <div className="m-4">
              <Link href="/album">
                <a className="text-3xl text-orange-500">もっと見る</a>
              </Link>
            </div>
          </div>
        </div>

        <div className="m-auto">
          <div>
            <div className="flex justify-center pt-3 mb-3 text-3xl underline">
              New Album
            </div>
          </div>
          <div className="text-center">
            <div className="grid grid-cols-2 gap-y-5 justify-items-center sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 xl:grid-cols-6 2xl:grid-cols-7">
              {pets.map((img) => {
                return (
                  <div
                    key={img}
                    className="p-4 w-40 text-center bg-green-800 rounded-lg shadow-xl"
                  >
                    <div className="flex justify-center">
                      <Image
                        className="rounded-full object-none"
                        src={img}
                        width={128}
                        height={128}
                        alt="pet"
                      />
                    </div>
                    <div className="py-2 text-white">Name</div>
                    <button className="text-orange-600">Tap</button>
                  </div>
                );
              })}
            </div>
            <div className="m-4">
              <Link href="/album">
                <a className="text-3xl text-orange-500">もっと見る</a>
              </Link>
            </div>
          </div>
        </div>

        {/* <div>
          <div className="flex justify-center pt-3 my-3 text-3xl underline">
            New Photo
          </div>
          <div className="flex justify-center">
            <div className="grid md:grid-cols-2 gap-y-5 md:gap-5 lg:grid-cols-3 lg:gap-5">
              <div className="w-96 h-32 bg-green-800 rounded-lg">
                <div className="flex bg-sky-200">
                  <Image
                    className="bg-slate-400 object-none"
                    src="/images/onigiri.jpg"
                    width={100}
                    height={100}
                    alt="pet"
                  />
                  <div className="mx-auto">
                    <div className="text-white bg-slate-400">蘭太郎</div>
                    <p className="pl-3 w-60 h-8 bg-white">おにぎりちゃん</p>
                  </div>
                </div>
                <div className="text-center bg-blue-400">
                  <button className="text-orange-500 bg-green-300 ">Tap</button>
                </div>
              </div>
              <div className="w-96 h-32 bg-green-800 rounded-lg">
                <div className="flex bg-sky-200">
                  <Image
                    className="bg-slate-400 object-none"
                    src="/images/onigiri.jpg"
                    width={100}
                    height={100}
                    alt="pet"
                  />
                  <div className="mx-auto">
                    <div className="text-white bg-slate-400">蘭太郎</div>
                    <p className="pl-3 w-60 h-8 bg-white">おにぎりちゃん</p>
                  </div>
                </div>
                <div className="text-center bg-blue-400">
                  <button className="text-orange-500 bg-green-300 ">Tap</button>
                </div>
              </div>
            </div>

            <div className="bg-green-800 w-96">
              <div className="flex">
                <div>
                  <Image
                    src="/images/onigiri.jpg"
                    alt="pet"
                    width={80}
                    height={80}
                    className="rounded-full"
                  />
                </div>
                <div className="flex">
                  <p className="text-white px-2">Name</p>
                  <p className="text-white">time</p>
                </div>
                <div>
                  <Image
                    className="bg-slate-400 object-none"
                    src="/images/onigiri.jpg"
                    width={200}
                    height={200}
                    alt="pet"
                  />
                </div>
              </div>
              <div className="flex"></div>
            </div>

            <div>
              <div className="flex">
                <div>
                  <Image
                    src="/images/rantarou.jpg"
                    width={80}
                    height={80}
                    alt="pet"
                    className="rounded-full"
                  />
                </div>
                <div className="flex">
                  <p>name</p>
                  <p>time</p>
                </div>
                <div></div>
              </div>
              <div className="">
                <Image
                  src="/images/rantarou.jpg"
                  width={200}
                  height={200}
                  alt="pet"
                />
              </div>
            </div>
          </div>
        </div> */}

      </main>
      <Footer />
    </>
  );
};

export default Home;
